### ISSUE TITLE
Qu: How did you debug your Lambda function?

### ISSUE THREAD

**Issue by quantuminformation** [andene/github-repository-fetcher#1]

**Comment by khlbrg** [comment]
I my case I just ran it locally, with Node.

I haven't read up on how to debug Lambda functions. You can debug Node apps with --inspect flag.

https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27

**Comment by quantuminformation** [comment]
I was wondering if serverless-offline would help in this case.

**Comment by khlbrg** [comment]
Yeah I guess it would be an option.

Another alternative could be: https://github.com/localstack/localstack
